Roll20-Pathfinder-Character-Sheet/Roll20-Pathfinder-Character-Sheet

- src/PFConst.js
- src/PFHealth.js
- src/PFInitiative.js
- src/PFSheet.js
- src/SWUtils.js
- src/index.html
includes latest changes from Chris's fork
> Roll20 pathfinder character sheet master

- src/PFClassRaceGrid.js
- src/PFDefense.js
- src/PFHealth.js
- src/PFNPC.js
- src/PFSkills.js
- src/PFSpellCasterClasses.js
- src/PFSpells.js
- src/SWUtils.js
> final exports this should be it

- src/PFInventory.js
- src/PFMigrate.js
- src/PFSkills.js
- src/PFSpells.js
- src/index.html
more forgiving of class and level in spells menu
do not total spells if 'manual' is checked
use same field for total if manual or auto, have them switch in spells per day section
> attempt to fix spells menu

- src/PFSpells.js
1. pay attention to sort
2. add exception handling
> spellmenu fixes

- .jshintrc
- src/HLImport.js
remove commas from end of functions
add import statements to top
don't touch anything else
> fixup hlimport for es6

- src/index.html
> 3rd try remove whisper from prodsupport

- src/PFConst.js
- src/index.html
- src/sheet.json
make merge buttons only appear if old lists checked
added announcements
> update announcements and buttons

- src/PFDefense.js
- src/PFInventory.js
- src/PFSpells.js
- src/index.html
- src/pathfinder.css
- src/translate.json
fix spell updates when updating dc
fix reset of cmd and ac having different abilities
move top buttons outside of labels to make faster and also hopefully less locking
> prod support 142+

- src/PFInventory.js
- src/PFSheet.js
- src/index.html
- src/pathfinder.css
fix value , hp, weight for equipment list, also qty, qty_max
fix spells per day to remove prepared totals
fix class dropdown
fix extra damage textbox so outer div expands on spell rows
> more fixes to 1.44

- src/PFAbility.js
- src/PFInventory.js
> fix item link and ability spell reisst

- src/index.html
- src/pathfinder.css
- src/translate.json
also a few css fixes for the sheet-cssbuttons
> added pretty buttons for dual wield

- src/PFAbility.js
- src/PFAttacks.js
- src/PFBuffs.js
- src/PFConst.js
- src/PFUtils.js
- src/SWUtils.js
- src/index.html
fix swutil parsing - which fixes item compendium and probably other compendiums
fix 2 small bugs to parsing equations for buffs (and for other)
update to 151
keeps vinces changes
> small fixes for 1.51

- src/PFConst.js
- src/PFNPCParser.js
fix line in init where calling variable by wrong name causing all parsing to fail
> FIX TO NPC PARSING

- src/PFEncumbrance.js
- src/PFSheet.js
- src/PFSize.js
- src/index.html
- src/sheet.json
- src/translate.json
grab latest announcements and prod support updates
> latest prod support

- src/PFBuffs.js
buffs with bonus types enabled will now stack correctly with other fields on the sheet, except skills.
> stack buffs with sheet fields

- src/PFAttacks.js
- src/PFNPCParser.js
- src/PFSheet.js
- src/PFSpells.js
- src/index.html
damage mult dropdown
spell level dropdown in spell rows
> fix to dropdowns

- src/PFAttacks.js
- src/PFConst.js
- src/PFSheet.js
- src/PFSpells.js
- src/index.html
allows more than just 1.5 or 1
> v 1.55 master branch fix to damage multiplier

- src/PFMigrate.js
- src/PFNPCParser.js
- src/PFSheet.js
- src/PFSkills.js
- src/PFSpells.js
- src/index.html
- src/pathfinder.css
- src/sheet.json
> Copy of develop BEFORE merge no @{} dropdown version

- src/PFConst.js
- src/PFDefense.js
- src/PFSheet.js
- src/PFSize.js
- src/index.html
- src/pathfinder.css
- src/translate.json
Fix to damage dice when changing size between small and medium: 
Fix to frequency showing on new abilities even when N/A
> V1.58 size fix

- src/PFSheet.js
- src/index.html
add announcement to top. no other changes
> add announcements for 1.6x

- src/HLImport.js
Now sets attributes silently, and does not manually trigger recalc, to
improve sheet responsiveness after importing. Macros for new spells
won't work properly at first as a result; toggling something on/off
under Spell Roll Options will force an update for all spells.
Many numbers that were left to auto-calculate are now imported (due to
no longer triggering recalc)
Fixed spells-as-weapons crashing item import
Work-around for specialist wizard names and spell importing
Now supports 10 Craft/Lore/Perform/Profession/misc skills (up from
3/3/3/3/5), and sets number of such skills to show
Adds skill situational bonuses to notes, instead of trying to rebuild
skill macros
Imports creature types & subtypes, base speed, character description
Auto-detects PFS characters
Imports prestige/fame from …
> HL Import update

- src/PFBuffs.js
- src/PFSheet.js
last minute fix to bug user found
> fix dodge calculation

- src/HLImport.js
- src/PFConst.js
- src/PFSize.js
> 1.67, Herolab and compendium imports fixes

- src/PFConst.js
- src/PFMenus.js
- src/PFNPCParser.js
- src/PFSheet.js
- src/PFSpellOptions.js
- src/index.html
- src/pathfinder.css
- src/translate.json
> pathfinder 1.692

- src/PFConst.js
- src/PFNPCParser.js
- src/PFSheet.js
- src/PFUtils.js
- src/index.html
> npc parse fix

- src/PFConst.js
- src/index.html
NPC Parse fixed 
Weapon parse fixed 
Dmg buff updates to attacks fixed 
ACP not resetting fixed
> 1.699 fixes to dmg buffs and other

- src/PFAttacks.js
- src/PFConst.js
- src/PFDefense.js
- src/PFSkills.js
- src/index.html
NPC Parse fixed 
Weapon parse fixed 
Dmg buff updates to attacks fixed 
ACP not resetting fixed
> 1.699 parse fixes dmg buff fixes

- src/PFAttackGrid.js
- src/PFAttacks.js
- src/PFEncumbrance.js
- src/PFSpellOptions.js
- src/PFTemplate.js
- src/PFUtilsAsync.js
- src/SWUtils.js
Fix spell roll resetting cast def bonus on recalc
Fix attack row damage on ability dropdown change if max or mult applies
Fix speed penalties not stacking
Remove rounding on speed when dividing due to penalties
Add event to change speed when is dwarf checked
Add border to run speed when affected by heavy encumbrance
> fix encumbrance and spell bugs

- src/PFAttacks.js
- src/PFBuffs.js
- src/PFSize.js
upload and test size changes
size change to dropdown correctly updates attacks, it was doing it wrong
buff size change overrides manual dropdown (if they try to change dropdown it resets)
> fix to size

- src/HLImport.js
HL-Import: Added importing of "defensive" abilities (Uncanny Dodge, Evasion, etc).
> HL-Import: Defensive abilities

- src/index.html
Fixed width of the concentration check button for spell class 1 and 2.
Fixed the class of a column of +s for spell class 0.
Added missing border for spell class 2.
> fixed visual issues with spellcasting classes
